# Generated by Django 3.0.5 on 2020-05-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksave',
            name='currentuser',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
