# Generated by Django 3.0.5 on 2020-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomodel',
            name='currentuser',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
